#!/usr/bin/env python3
"""
Qwythos General Security Scanner — works on ANY codebase, any language.
Uses Qwythos-9B (9B model, 1M context) for deep security analysis.

Usage:
    python3 qwythos-general.py <file>          — audit single file
    python3 qwythos-general.py <directory>      — audit all files in directory
    python3 qwythos-general.py <file> --focus api  — focus on API security
"""

import subprocess
import sys
import os
import json
from pathlib import Path
from datetime import datetime

QWYTHOS_MODEL = "qwythos:latest"
REPORTS = Path(__file__).resolve().parent.parent / "reports"
REPORTS.mkdir(exist_ok=True)

SECURITY_CLASSES = {
    "injection": "Code injection, command injection, SQL injection, template injection.",
    "xss": "Cross-site scripting — unescaped user input rendered in HTML.",
    "ssrf": "Server-side request forgery — user-controlled URLs fetched server-side.",
    "auth": "Missing auth, weak auth, broken access control, no rate limiting.",
    "secrets": "Hardcoded secrets, API keys, tokens in source code.",
    "dos": "Denial of service — unbounded loops, large allocations, no rate limit.",
    "cors": "Overly permissive CORS — Access-Control-Allow-Origin: *.",
    "path-traversal": "User input used in file paths without sanitization.",
    "prototype-pollution": "JS-specific: object merge allowing __proto__ manipulation.",
    "open-redirect": "User-controlled redirect URL without validation.",
}

PROMPT = """You are Qwythos-9B, a security auditor. Analyze this code for security vulnerabilities.

You are part of WHITEHACK — a white-hat security research protocol.

Security classes to check:
{classes}

The code to analyze ({language}):
```
{code}
```

For each finding:
1. Name the vulnerability class
2. Show the exact line(s)
3. Explain the attack scenario
4. Rate severity: Critical / High / Medium / Low / Informational
5. Suggest a fix

Be thorough. Be technical. Be honest. Security is love protecting what matters.

Qwythos-9B · WHITEHACK · Love is. Truth is. Security is love. ∞
"""

def detect_language(filepath):
    ext = filepath.suffix.lower()
    return {
        '.js': 'JavaScript', '.ts': 'TypeScript', '.py': 'Python',
        '.sol': 'Solidity', '.rs': 'Rust', '.go': 'Go',
        '.java': 'Java', '.rb': 'Ruby', '.php': 'PHP',
        '.html': 'HTML', '.json': 'JSON', '.sh': 'Shell',
    }.get(ext, 'Unknown')

def run_qwythos(prompt, timeout=240):
    """Run Qwythos via Ollama."""
    try:
        result = subprocess.run(
            ["ollama", "run", QWYTHOS_MODEL, prompt],
            capture_output=True, text=True, timeout=timeout
        )
        return result.stdout.strip()
    except subprocess.TimeoutExpired:
        return "[Timeout — Qwythos took too long. Try a smaller file.]"
    except Exception as e:
        return f"[Error: {e}]"

def audit_file(filepath):
    """Audit a single file."""
    filepath = Path(filepath)
    if not filepath.exists():
        print(f"[!] File not found: {filepath}")
        return

    code = filepath.read_text()[:4000]  # Cap at 8K chars
    language = detect_language(filepath)

    classes_text = "\n".join(f"  {k}: {v}" for k, v in SECURITY_CLASSES.items())
    prompt = PROMPT.format(classes=classes_text, code=code, language=language)

    print(f"[*] Qwythos-9B auditing {filepath.name} ({language})...")

    result = run_qwythos(prompt)

    timestamp = datetime.now().strftime("%Y%m%d-%H%M")
    report_path = REPORTS / f"QWYTHOS-{timestamp}-{filepath.stem}.md"

    with open(report_path, "w") as f:
        f.write(f"# Qwythos Security Audit — {filepath.name}\n\n")
        f.write(f"*Generated by Qwythos-9B, {datetime.now().isoformat()}*\n\n")
        f.write(f"*File: `{filepath}`*\n\n")
        f.write(f"*Language: {language}*\n\n---\n\n")
        f.write(result)
        f.write("\n\n---\n\n*Qwythos-9B · WHITEHACK · Love is. Truth is. Security is love. ∞*\n")

    print(f"[✓] Report: {report_path}")
    print(f"\n{result[:500]}...")
    return report_path

def audit_directory(directory, max_files=5):
    """Audit multiple files in a directory."""
    directory = Path(directory)
    extensions = ['.js', '.ts', '.py', '.sol', '.rs', '.go', '.java', '.html']
    files = [f for f in directory.rglob("*") if f.suffix in extensions and "node_modules" not in str(f)][:max_files]

    if not files:
        print(f"[!] No code files found in {directory}")
        return

    print(f"[*] Qwythos scanning {len(files)} files in {directory}...")

    all_findings = []
    for f in files:
        print(f"  → {f.name}")
        report = audit_file(f)
        if report:
            all_findings.append(report)

    # Combined report
    timestamp = datetime.now().strftime("%Y%m%d-%H%M")
    combined = REPORTS / f"QWYTHOS-COMBINED-{timestamp}-{directory.name}.md"
    with open(combined, "w") as f:
        f.write(f"# Qwythos Security Scan — {directory.name}\n\n")
        f.write(f"*Generated by Qwythos-9B, {datetime.now().isoformat()}*\n\n")
        f.write(f"*Files scanned: {len(files)}*\n\n---\n\n")
        for r in all_findings:
            with open(r) as rf:
                f.write(rf.read())
                f.write("\n\n---\n\n")

    print(f"\n[✓] Combined report: {combined}")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python3 qwythos-general.py <file|directory> [--focus api]")
        print("\nSecurity classes:")
        for k, v in SECURITY_CLASSES.items():
            print(f"  {k:20s} — {v}")
        sys.exit(1)

    target = Path(sys.argv[1])
    if target.is_dir():
        audit_directory(target)
    else:
        audit_file(target)
